name: Locker
version: 1.1
author: michaelkrauty
main: me.michaelkrauty.Locker.Main
commands:
  locker:
    description: The locker command
    usage: /locker <args>
permissions:
  locker.lock:
    description: Allows creation of lockers
  locker.admin:
    description: Locker admin permission
    default: op